package com.outline.rules.lawyerssuppliments.newbusiness.realestate.commercial;
import com.util.Context;

rule "checkForeclosuresAndLoanWorkoutsAOPCommercial_Lawyers_old"
	when ctx : Context(this["foreclosuresCommercialPercentage"]>0 || this["loanWorkoutsCommercialPercentage"]>0)
	then
		ctx.put("question","Commercial Real estate forclosure work. Review commecial and residential and determine who they are doing it on behalf of a financial institution. If more than 25% needs C & F approval. If more than 10% of overall revenue, cannot offer more than 1,000,000 per claim limit.");
		ctx.put("hint","Review both Commercial and Residential Foreclosure and Loan workouts if the total percentage is greater than 25% of their overall revenue the account will be referred to C & F. If more than 10% subject to a max limit of 1M. Ask if they are doing it on behalf of a financial institution.");
end
rule "checkOtherCommercialAop_Lawyers_old"
	when ctx : Context(this["otherAopCommercialPercentage"]>0 )
	then
		ctx.put("question","Commercial Real estate 'Other' is greater than 0.");
		ctx.put("hint","Review the description and determine if it belongs in another category. Discuss with the client to understand what they are doing.");
end


rule "checkCommercialCombineAop_Lawyers_old"
	when ctx : Context(this["SpeculativeAopCommercialPercentage"]>0 || this["investmentTrustsPercentage"]>0 || this["estateSyndicationsAopCommercialPercentage"]>0 )
	then
		ctx.put("question","Decline - due Speculative Real Estate, Investment Trusts, or Real Estate Syndications.");
		ctx.put("hint","Decline - due Speculative Real Estate, Investment Trusts, or Real Estate Syndications.");
end